### ISSUE TITLE
identify and fix compatibility issues with ERPNext

### ISSUE THREAD

**Issue by harshit-30** [frappe/desk#594]

**Comment by kamaljohnson** [comment]
Common doctype `Service Level Agreement`
the issue faced: get_holidays called from `ticket.py` (uses Service Holiday List) or `issues.py` (uses Holiday List)

frappedesk sets a default holiday list in Service Holiday LIst if get_holidays is called from issue.py the Holiday List doctype is called, this throws an error since there is no Default Holiday List present
